version: '3.8'

services:
  housing-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: housing-api
    ports:
      - "8000:8000"
    volumes:
      # This mapping is CRITICAL. It lets the container see your local models folder.
      # If you retrain a model locally, the container sees the update immediately!
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    restart: always

  housing-ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: housing-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://housing-api:8000
    depends_on:
      - housing-api